### ISSUE TITLE
Admin edits

### ISSUE THREAD

**Issue by pelson** [ipython/xkcd-font#20]
As a follow-up activity to PR#17, I am looking to add a writeable deploy key as a secret in the .travis.yml. With this in place, we will get automatic commits of the built products that live in this repo (the fonts, and their previews).

We will also need to register a TravisCI hook for ipython/xkcd-font.

I'm happy to do both of these if I had admin privs, but equally happy to assist anybody else who may want to just get on and do it. One or the other would be great though 👍 

😄

**Comment by Carreau** [comment]
I should have sent you an invite to be admin. I can also help to set-up these deploy hooks. 

This is awesome !

**Comment by pelson** [comment]
Thanks @Carreau. Accepted. I'll add Travis to the repo.
