### ISSUE TITLE
Add lower case letters

### ISSUE THREAD

**Issue by seanthegeek** [ipython/xkcd-font#9]
I realize the last update was four months ago, but would it be possible to add lower case letters? They are necessary for syntactically correct programs like this:

http://xkcd.com/221/

**Comment by thenoncoder** [comment]
I uploaded an SVG version of those lowercase letters : 
http://s000.tinyupload.com/index.php?file_id=07866014825679058993

SHA-256 : CC64316F08254EE4976A02BE1AEE2C743C49090443F4AFC6F0C5B08F23E68620

**Comment by thenoncoder** [comment]
@randallmunroe, can you upload a single png file of a hi-res scan of every single letter and number and symbol etc? That would be a lot better than having a lot of files, and better than writing complete words and sentences.
If you do provide the file, I'll vectorize it, and it if I have time, I'll also make a proper font outta it.

**Comment by ellisonbg** [comment]
Did you see that we do have this:

https://github.com/ipython/xkcd-font/blob/master/rawdata/lowercase/lowercase-glyphs.png

On Tue, Jul 14, 2015 at 10:40 AM, thenoncoder <notifications@github.com>
wrote:

> @randallmunroe <https://github.com/randallmunroe>, can you upload a
> single png file of a hi-res scan of every single letter and number and
> symbol etc? That would be a lot better than having a lot of files, and
> better than writing complete words and sentences.
> If you do provide the file, I'll vectorize it, and it if I have time, I'll
> also make a proper font outta it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/xkcd-font/issues/9#issuecomment-121285004>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by thenoncoder** [comment]
@ellisonbg There are no mathematical glyphs though, and that was what I was talking about!

**Comment by ellisonbg** [comment]
Ahh, missed that.

On Tue, Jul 21, 2015 at 6:42 AM, thenoncoder <notifications@github.com>
wrote:

> @ellisonbg <https://github.com/ellisonbg> There are no mathematical
> glyphs though, and that was what I was talking about!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/xkcd-font/issues/9#issuecomment-123309071>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by randallmunroe** [comment]
Don't know which part it's helpful with, but here's a big file with two
versions of uppercase letters (I did this twice, I forgot), the lowercase
ones from before, and every common punctuation/math symbol I could think of
offhand :)

Temporary link, in case attachments don't work:

http://xkcd.com/temp/many-glyphs.png

**Comment by rgbkrk** [comment]
Reattached the many-glyphs.png:

![many-glyphs](https://cloud.githubusercontent.com/assets/836375/9048313/d75187b8-39fd-11e5-933a-6c50552e3a0b.png)

Thanks Randall!

**Comment by HughP** [comment]
Thank you Randall!!

BTW: Any hope for (IPA Characters](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet) re #11  ?

**Comment by kakumarabhishek** [comment]
Hi! Any progress with the lowercase letters?

**Comment by takluyver** [comment]
I don't think anyone has been working on this for quite a while.

**Comment by spu7nik** [comment]
Lower case letters are done by me, but still there is a little problem with the thickness of the uppercase and lowercase letters. I'm not good enough to extract them of a png file, but if we can get them in a vector graphic type i'll merge them together in one file. Also there is a known bug in Gimp. The newest font version doesn't work with GIMP (for me, maybe someone will test this) The letters are crumbled in some way. But they do work in MS Office Word, newest Photoshop version and HTML/CSS.

**Comment by rgbkrk** [comment]
Closed in #13, #15.
